#!/usr/bin/env python
"""One-off: write the numbered pipeline notebooks with real, runnable, project-
specific walkthrough cells (so the notebooks ARE the process record).

This mirrors the logic in scripts/ingest.py + scripts/make_charts.py but laid out
as the numbered pipeline a reader can step through:
    00-explore  (left as-is: DuckDB sandbox)
    01-ingest   fetch BOM adjusted chart -> data/raw/
    02-clean    parse + clean in DuckDB -> films_adjusted (+ _sources)
    03-prepare  package the export (CSV + codebook)
    04-viz      matplotlib exploration (adjusted vs nominal)
    06-viz-social  the shared lollipop dumbbell lead chart (inline + saved)

Run once: .venv/bin/python scripts/_build_notebooks.py
"""

from __future__ import annotations

import json
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent.parent / "notebooks"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": _src(lines)}


def _src(lines: tuple[str, ...]) -> list[str]:
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def write(name: str, cells: list[dict]) -> None:
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    (NB_DIR / name).write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {name} ({len(cells)} cells)")


BOOT = (
    "import sys, os\n"
    "from pathlib import Path\n"
    "PROJECT = Path.cwd()\n"
    "while not (PROJECT / 'config.yaml').exists() and PROJECT != PROJECT.parent:\n"
    "    PROJECT = PROJECT.parent\n"
    "os.chdir(PROJECT)\n"
    "sys.path.insert(0, str(PROJECT))"
)


# ---------------------------------------------------------------------------
# 01 — INGEST
# ---------------------------------------------------------------------------
ingest = [
    md("# 01 — Ingest",
       "",
       "Fetch the raw source and land it in `data/raw/` **untouched**.",
       "",
       "**Source:** Box Office Mojo — *Top Lifetime Adjusted Grosses* (domestic). The",
       "`?adjust_gross_to=2022` query param makes the page return each film's",
       "inflation-adjusted gross (in 2022 dollars) alongside its nominal gross,",
       "estimated tickets sold, and release year. With that param the page is static",
       "(no JS needed)."),
    code(BOOT, "",
         "import pandas as pd",
         "from io import StringIO",
         "from src.ingest import load_config, fetch_html",
         "",
         "cfg = load_config('config.yaml')",
         "src = cfg['sources']['bom_adjusted']",
         "url = src['url']",
         "print('Source URL:', url)"),
    md("## Fetch and cache the raw HTML",
       "Save the page to `data/raw/` so the raw source is preserved and re-runs are",
       "offline."),
    code("raw_path = Path(cfg['paths']['data_raw']) / 'bom_top_lifetime_adjusted_2022.html'",
         "raw_path.parent.mkdir(parents=True, exist_ok=True)",
         "",
         "if raw_path.exists():",
         "    print('Using cached raw HTML:', raw_path)",
         "    html = raw_path.read_text(encoding='utf-8')",
         "else:",
         "    html = fetch_html(url)",
         "    raw_path.write_text(html, encoding='utf-8')",
         "    print('Saved raw HTML ->', raw_path)",
         "",
         "print(f'{len(html):,} bytes')"),
    md("## Parse the chart table",
       "The page has a single table: Rank, Title, Adj. Lifetime Gross, Lifetime Gross,",
       "Est. Num Tickets, Year."),
    code("raw = pd.read_html(StringIO(html))[0]",
         "print(raw.shape)",
         "raw.head(10)"),
    md("## Also fetch the WORLDWIDE chart",
       "The adjusted chart above is **domestic only** (U.S. & Canada). To compare",
       "domestic vs. international we also pull Box Office Mojo's worldwide chart,",
       "which splits each film into worldwide / domestic / foreign gross."),
    code("ww_url = cfg['sources']['bom_worldwide']['url']",
         "ww_path = Path(cfg['paths']['data_raw']) / 'bom_ww_top_lifetime.html'",
         "if ww_path.exists():",
         "    ww_html = ww_path.read_text(encoding='utf-8')",
         "else:",
         "    ww_html = fetch_html(ww_url)",
         "    ww_path.write_text(ww_html, encoding='utf-8')",
         "ww_raw = pd.read_html(StringIO(ww_html))[0]",
         "print(ww_raw.shape)",
         "ww_raw.head(5)"),
    md("## Third source: film GENRE from the TMDB API",
       "",
       "Box Office Mojo has **no genre column**, so genre is a *third data source* we",
       "ingest here — from **TMDB** (The Movie Database) via its REST API.",
       "",
       "**This step requires a free API key.** Get one at themoviedb.org (Settings →",
       "API) and put it in the project's `.env` file (gitignored, never committed):",
       "",
       "```",
       "TMDB_API_KEY=your_key_here",
       "```",
       "",
       "For each film we call `GET /3/search/movie?query=<title>&year=<year>`, take the",
       "first result, and map its `genre_ids` to names via `GET /3/genre/movie/list`.",
       "The HTTP call itself lives in `src/ingest.py` → `tmdb_lookup_movie()` (per the",
       "workspace norm that fetch logic lives in `src/`), and every response is **cached",
       "as JSON in `data/raw/tmdb/`** so this raw data is preserved and re-runs are",
       "offline. The next cell makes **one call explicitly** so the mechanics are visible."),
    code("import requests",
         "from src.ingest import load_env, tmdb_genre_map, tmdb_lookup_movie",
         "",
         "load_env('.env')  # load TMDB_API_KEY from the gitignored .env",
         "api_key = os.environ.get('TMDB_API_KEY')",
         "assert api_key, 'TMDB_API_KEY missing from .env — see the note above'",
         "",
         "# One raw TMDB call, spelled out, so you can see what the API returns:",
         "demo = requests.get('https://api.themoviedb.org/3/search/movie',",
         "                    params={'api_key': api_key, 'query': 'Avatar', 'year': 2009}, timeout=20)",
         "top = demo.json()['results'][0]",
         "print('HTTP', demo.status_code, '| result:', top['title'], top['release_date'])",
         "print('raw genre_ids:', top['genre_ids'])",
         "print('mapped genres:', [tmdb_genre_map(api_key)[i] for i in top['genre_ids']])"),
    md("### Ingest genre for every film",
       "Take the film list straight from the two raw box-office tables just fetched, and",
       "look up each on TMDB (first run hits the API ~321 times, rate-limited; re-runs",
       "read the JSON cache in `data/raw/tmdb/`). The raw genre records are saved to",
       "`data/raw/tmdb_genres.parquet` — this is the ingested genre data that",
       "`02-clean.ipynb` will load into DuckDB (no API calls happen in cleaning)."),
    code("# film list from the raw tables (title + year), deduped",
         "adj_titles = raw[['Title', 'Year']].rename(columns={'Title':'title','Year':'release_year'})",
         "ww_titles  = ww_raw[['Title', 'Year']].rename(columns={'Title':'title','Year':'release_year'})",
         "titles = pd.concat([adj_titles, ww_titles]).drop_duplicates().reset_index(drop=True)",
         "titles['release_year'] = titles['release_year'].astype(int)",
         "",
         "recs = [tmdb_lookup_movie(r['title'], int(r['release_year']), api_key, cfg)",
         "        for _, r in titles.iterrows()]",
         "genre_raw = pd.DataFrame(recs)",
         "genre_raw['genres_str'] = genre_raw['genres'].apply(lambda g: ', '.join(g) if g else None)",
         "genre_raw.to_parquet(Path(cfg['paths']['data_raw']) / 'tmdb_genres.parquet')",
         "print(f'{genre_raw[\"matched\"].sum()}/{len(genre_raw)} films matched on TMDB')",
         "genre_raw[['title','year','primary_genre','genres_str']].head(10)"),
    md("### Also ingest each film's COUNTRY OF ORIGIN (TMDB)",
       "",
       "Box Office Mojo's \"domestic\" means **U.S. & Canada** — which only equals a",
       "film's *home market* for U.S.-made films. For a Chinese film like *Ne Zha 2*,",
       "its money earned in China is bucketed as \"foreign,\" which would make it look",
       "like a film that conquered the world when it really conquered its home market.",
       "",
       "So we also pull each film's **origin country** from TMDB's movie-detail",
       "endpoint (`GET /3/movie/{id}`, via `tmdb_movie_country()` in `src/ingest.py`,",
       "cached in `data/raw/tmdb/`). The `is_us` flag lets the domestic-vs-international",
       "analysis stay consistent (home vs abroad) by restricting to U.S.-made films.",
       "Non-U.S. films are kept in the data for a separate 'foreign films in the U.S.",
       "market' angle."),
    code("from src.ingest import tmdb_movie_country",
         "",
         "country_rows = []",
         "for r in genre_raw.to_dict('records'):",
         "    if r.get('tmdb_id'):",
         "        c = tmdb_movie_country(int(r['tmdb_id']), api_key, cfg)",
         "        country_rows.append({'tmdb_id': int(r['tmdb_id']),",
         "            'origin_country': ', '.join(c['origin_country']) if c['origin_country'] else None,",
         "            'is_us': c['is_us']})",
         "country_raw = pd.DataFrame(country_rows).drop_duplicates('tmdb_id')",
         "country_raw.to_parquet(Path(cfg['paths']['data_raw']) / 'tmdb_countries.parquet')",
         "print(f'{int(country_raw[\"is_us\"].sum())} US-made / {len(country_raw)-int(country_raw[\"is_us\"].sum())} non-US')",
         "country_raw['origin_country'].value_counts().head(8)"),
    md("---",
       "**Next:** `02-clean.ipynb` loads all three raw sources into DuckDB and cleans",
       "them.",
       "",
       "Nothing here modified data — the raw HTML and the TMDB JSON in `data/raw/` are",
       "the untouched ingested sources."),
]


# ---------------------------------------------------------------------------
# 02 — CLEAN
# ---------------------------------------------------------------------------
clean = [
    md("# 02 — Clean & Standardize",
       "",
       "Load the raw chart into DuckDB and clean it **in SQL** (workspace norm):",
       "strip `$`/commas, cast to numeric, derive `decade` and the `inflation_multiple`",
       "(adjusted / nominal). Result: the `films_adjusted` table."),
    code(BOOT, "",
         "import pandas as pd",
         "from io import StringIO",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection, load_to_duckdb, run_sql, register_source, save_interim",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "",
         "# Reload the raw HTML parsed in 01 into a raw DuckDB table.",
         "html = (Path(cfg['paths']['data_raw']) / 'bom_top_lifetime_adjusted_2022.html').read_text(encoding='utf-8')",
         "raw = pd.read_html(StringIO(html))[0]",
         "load_to_duckdb(raw, 'bom_raw', con)",
         "print('bom_raw:', con.execute('SELECT COUNT(*) FROM bom_raw').fetchone()[0], 'rows')"),
    md("## Clean in DuckDB",
       "Money strings (`$1,895,421,694`) become `BIGINT`; `decade` uses integer",
       "division; `inflation_multiple` = adjusted / nominal (how many times the film's",
       "original take the adjusted figure represents)."),
    code("films = run_sql('''",
         "    SELECT",
         "        CAST(\"Rank\" AS INTEGER)                                   AS rank_adjusted,",
         "        \"Title\"                                                   AS title,",
         "        CAST(REGEXP_REPLACE(\"Adj. Lifetime Gross\", '[$,]', '', 'g') AS BIGINT) AS adjusted_gross,",
         "        CAST(REGEXP_REPLACE(\"Lifetime Gross\",       '[$,]', '', 'g') AS BIGINT) AS nominal_gross,",
         "        CAST(\"Est. Num Tickets\" AS BIGINT)                        AS est_tickets,",
         "        CAST(\"Year\" AS INTEGER)                                   AS release_year,",
         "        (CAST(\"Year\" AS INTEGER) // 10) * 10                      AS decade,",
         "        ROUND(",
         "            CAST(REGEXP_REPLACE(\"Adj. Lifetime Gross\", '[$,]', '', 'g') AS DOUBLE)",
         "            / NULLIF(CAST(REGEXP_REPLACE(\"Lifetime Gross\", '[$,]', '', 'g') AS DOUBLE), 0),",
         "            2) AS inflation_multiple",
         "    FROM bom_raw",
         "    ORDER BY adjusted_gross DESC",
         "''', con)",
         "load_to_duckdb(films, 'films_adjusted', con)",
         "print(films.shape)",
         "films.head(10)"),
    md("## Quick sanity checks"),
    code("# The classics should dominate the adjusted board; recent blockbusters have",
         "# the smallest inflation multiples (little time for ticket prices to rise).",
         "print('Top adjusted:', films.iloc[0]['title'], films.iloc[0]['release_year'])",
         "print('No nulls in key cols:',",
         "      films[['adjusted_gross','nominal_gross','est_tickets','release_year']].notna().all().all())",
         "films[['title','release_year','inflation_multiple']].sort_values('inflation_multiple').head(5)"),
    md("## Clean the WORLDWIDE chart (domestic vs international split)",
       "Same money-string cleaning; a bare `-` (no gross in a market) becomes NULL.",
       "Produces `films_worldwide` with domestic/foreign/worldwide gross + the split."),
    code("ww_html = (Path(cfg['paths']['data_raw']) / 'bom_ww_top_lifetime.html').read_text(encoding='utf-8')",
         "ww_raw = pd.read_html(StringIO(ww_html))[0]",
         "load_to_duckdb(ww_raw, 'bom_ww_raw', con)",
         "ww = run_sql('''",
         "    WITH cleaned AS (",
         "        SELECT CAST(\"Rank\" AS INTEGER) AS rank_worldwide, \"Title\" AS title,",
         "               CAST(\"Year\" AS INTEGER) AS release_year,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Worldwide Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS worldwide_gross,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Domestic Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS domestic_gross,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Foreign Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS foreign_gross",
         "        FROM bom_ww_raw)",
         "    SELECT rank_worldwide, title, worldwide_gross, domestic_gross, foreign_gross, release_year,",
         "        ROUND(100.0*domestic_gross/NULLIF(worldwide_gross,0),1) AS domestic_pct,",
         "        ROUND(100.0*foreign_gross /NULLIF(worldwide_gross,0),1) AS foreign_pct",
         "    FROM cleaned ORDER BY worldwide_gross DESC''', con)",
         "load_to_duckdb(ww, 'films_worldwide', con)",
         "print('most international (lowest domestic %):')",
         "print(ww.nsmallest(5,'domestic_pct')[['title','release_year','worldwide_gross','domestic_pct']].to_string(index=False))",
         "ww.head()"),
    md("## Load the genre data (ingested from TMDB in 01)",
       "",
       "The TMDB genre lookup was done in `01-ingest` (that's where external sources are",
       "pulled — see the API-key note there). Here we just **load** the ingested genre",
       "records from `data/raw/tmdb_genres.parquet` into DuckDB — no API calls in the",
       "cleaning stage. Builds `films_genre` (one row per film) and `film_genres_long`",
       "(one row per film x genre, which drives the genre market-split analysis)."),
    code("genre_raw = pd.read_parquet(Path(cfg['paths']['data_raw']) / 'tmdb_genres.parquet')",
         "country_raw = pd.read_parquet(Path(cfg['paths']['data_raw']) / 'tmdb_countries.parquet')",
         "",
         "films_genre = (genre_raw.drop(columns=['genres']).rename(columns={'year':'release_year'})",
         "               .merge(country_raw, on='tmdb_id', how='left')",
         "               .drop_duplicates(['title','release_year']))  # one row per film",
         "load_to_duckdb(films_genre, 'films_genre', con)",
         "",
         "long_rows = [{'title': r['title'], 'release_year': r['year'], 'genre': g}",
         "             for r in genre_raw.to_dict('records') for g in r['genres']]",
         "film_genres_long = pd.DataFrame(long_rows).drop_duplicates()",
         "load_to_duckdb(film_genres_long, 'film_genres_long', con)",
         "print(f'{films_genre[\"matched\"].sum()}/{len(films_genre)} matched; '",
         "      f'{int(films_genre[\"is_us\"].sum())} US-made; {len(film_genres_long)} film-genre rows')",
         "films_genre['primary_genre'].value_counts().head(8)"),
    md("## Save interim + register provenance"),
    code("save_interim(films, cfg, 'films_adjusted.parquet')",
         "save_interim(ww, cfg, 'films_worldwide.parquet')",
         "save_interim(films_genre, cfg, 'films_genre.parquet')",
         "save_interim(film_genres_long, cfg, 'film_genres_long.parquet')",
         "",
         "register_source(con, 'films_adjusted',",
         "    name='Box Office Mojo - Top Lifetime Adjusted Grosses (domestic)',",
         "    url=cfg['sources']['bom_adjusted']['url'], license='Data (c) IMDb/Box Office Mojo.',",
         "    notes='Domestic (US/Canada). Adjusted to 2022 $ via tickets x 2022 avg ticket price (ticket-price inflation, NOT CPI).',",
         "    methodology='Tickets sold x reference-year avg price; lifetime totals include re-releases.',",
         "    series_breaks='Nominal grosses are year-of-release dollars, not comparable across eras.')",
         "register_source(con, 'films_worldwide',",
         "    name='Box Office Mojo - Top Lifetime Grosses (Worldwide)',",
         "    url=cfg['sources']['bom_worldwide']['url'], license='Data (c) IMDb/Box Office Mojo.',",
         "    notes='Worldwide/domestic/foreign lifetime gross (NOMINAL $) + split. Domestic = US & Canada.',",
         "    methodology='Studio-reported theatrical receipts; lifetime totals include re-releases.',",
         "    series_breaks='Nominal dollars; worldwide totals favor recent wide-release films.')",
         "register_source(con, 'films_genre',",
         "    name='TMDB - film genres', url='https://www.themoviedb.org/',",
         "    license='TMDB API; non-commercial attribution.',",
         "    notes='Genre(s) per film matched by title+year. Multi-genre; used as a ratio in the market split.',",
         "    methodology='TMDB /search/movie by title+year, first result.', series_breaks='')",
         "print(con.execute('SELECT duckdb_table, source_name FROM _sources ORDER BY duckdb_table').df().to_string(index=False))"),
    md("---",
       "**Next:** `03-prepare.ipynb` packages the three exports + codebooks."),
    md("## Cleanup",
       "Close the DuckDB connection so the write lock is released."),
    code("con.close()",
         "print('connection closed')"),
]


# ---------------------------------------------------------------------------
# 03 — PREPARE
# ---------------------------------------------------------------------------
prepare = [
    md("# 03 — Prepare & Export",
       "",
       "Package the cleaned `films_adjusted` table as the published dataset: CSV",
       "(+ Excel/Parquet) with a plain-English codebook for every column."),
    code(BOOT, "",
         "import pandas as pd",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection",
         "from src.prepare import package_dataset",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "films = con.execute('SELECT * FROM films_adjusted ORDER BY adjusted_gross DESC').df()",
         "worldwide = con.execute('SELECT * FROM films_worldwide ORDER BY worldwide_gross DESC').df()",
         "genre = con.execute('SELECT * FROM films_genre ORDER BY title').df()",
         "print('adjusted', films.shape, '| worldwide', worldwide.shape, '| genre', genre.shape)"),
    md("## Codebook — a plain-English description for every column"),
    code("codebook = {",
         "    'rank_adjusted':     'Rank by inflation-adjusted domestic gross (1 = highest).',",
         "    'title':             'Film title.',",
         "    'adjusted_gross':    'Domestic lifetime gross adjusted to 2022 dollars via ticket-price inflation (USD).',",
         "    'nominal_gross':     'Domestic lifetime gross in year-of-release dollars, as originally reported (USD).',",
         "    'est_tickets':       'Estimated number of tickets sold over the film lifetime (Box Office Mojo estimate).',",
         "    'release_year':      'Year of the film original theatrical release.',",
         "    'decade':            'Release decade (release_year rounded down to the nearest 10).',",
         "    'inflation_multiple':'adjusted_gross / nominal_gross - how many times its original take the adjusted figure represents.',",
         "}",
         "",
         "notes = '''",
         "Source: Box Office Mojo, Top Lifetime Adjusted Grosses (domestic, US/Canada), adjusted to 2022 dollars.",
         "URL: https://www.boxofficemojo.com/chart/top_lifetime_gross_adjusted/?adjust_gross_to=2022",
         "",
         "Method: adjusted gross = estimated tickets sold x the 2022 average ticket price (ticket-price inflation,",
         "NOT CPI). Domestic only. A film lifetime total includes re-release grosses, which inflates some classics.",
         "Nominal grosses are in year-of-release dollars and are not comparable across eras without the adjustment.",
         "'''",
        "written = package_dataset(films, cfg, name='highest_grossing_films_v1', codebook=codebook, notes=notes)",
         "written"),
    md("## Package the worldwide + genre exports"),
    code("ww_codebook = {",
         "    'rank_worldwide': 'Rank by worldwide lifetime gross (1 = highest).',",
         "    'title': 'Film title.',",
         "    'worldwide_gross': 'Worldwide lifetime gross, nominal USD (domestic + foreign).',",
         "    'domestic_gross': 'Domestic (U.S. & Canada) lifetime gross, nominal USD.',",
         "    'foreign_gross': 'International (rest-of-world) lifetime gross, nominal USD.',",
         "    'release_year': 'Year of original theatrical release.',",
         "    'domestic_pct': 'Domestic gross as a percent of worldwide.',",
         "    'foreign_pct': 'International gross as a percent of worldwide.',",
         "}",
         "ww_notes = '''Source: Box Office Mojo, Top Lifetime Grosses (Worldwide).",
         "Nominal (year-of-release) dollars, NOT inflation-adjusted. Domestic = US & Canada.'''",
         "package_dataset(worldwide, cfg, name='films_worldwide_v1', codebook=ww_codebook, notes=ww_notes)",
         "",
         "genre_codebook = {",
         "    'title': 'Film title.', 'release_year': 'Release year (match key).',",
         "    'tmdb_id': 'TMDB movie id.', 'tmdb_title': 'Title as returned by TMDB.',",
         "    'primary_genre': \"TMDB's first-listed genre for the film.\",",
         "    'genres_str': 'All TMDB genres, comma-separated.',",
         "    'matched': 'True if a TMDB result was found for title+year.',",
         "}",
         "genre_notes = '''Source: TMDB (themoviedb.org), matched by title + release year.",
         "Genres are TMDB editorial tags; most films have several. Used as a ratio in the",
         "genre market-split analysis (see SOURCES.md for the multi-genre attribution note).'''",
         "package_dataset(genre, cfg, name='films_genre_v1', codebook=genre_codebook, notes=genre_notes)"),
    md("---",
       "**Next:** `04-viz.ipynb` (exploration) and `06-viz-social.ipynb` (the three social charts)."),
    md("## Cleanup"),
    code("con.close()",
         "print('connection closed')"),
]


# ---------------------------------------------------------------------------
# 04 — VIZ (matplotlib exploration)
# ---------------------------------------------------------------------------
viz = [
    md("# 04 — Explore visually",
       "",
       "Explore the project's three story angles before building the publication",
       "charts, using the shared Pillow templates. Charts render inline via `display()`.",
       "",
       "- **A. Domestic** — adjusted vs nominal gross (dumbbell)",
       "- **B. Worldwide** — domestic vs international split (dumbbell)",
       "- **C. Genre** — which genres skew international vs domestic (diverging bars)",
       "",
       "> Note: this project renders with the shared **Pillow** factory rather than",
       "> matplotlib. (matplotlib does not run in this project's Python 3.14 venv — a",
       "> known `MarkerStyle` deepcopy recursion during axis-tick rendering — and the",
       "> publication path is Pillow anyway, so matplotlib isn't a dependency here.)"),
    code(BOOT, "",
         "WORKSPACE = PROJECT.parent.parent",
         "sys.path.insert(0, str(WORKSPACE / 'shared'))",
         "",
         "import pandas as pd, duckdb",
         "from src.ingest import load_config",
         "from chart_templates import lollipop, single_ranked_bars",
         "from viz import PRESETS",
         "from IPython.display import display",
         "",
         "cfg = load_config('config.yaml')",
         "# read-only: this notebook only reads, so it runs even if another notebook",
         "# kernel has the DuckDB file open (DuckDB is single-writer).",
         "con = duckdb.connect(cfg['settings']['duckdb_file'], read_only=True)",
         "films = con.execute('SELECT * FROM films_adjusted ORDER BY adjusted_gross DESC LIMIT 15').df()",
         "films['label'] = films['title'] + '  (' + films['release_year'].astype(str) + ')'",
         "img_w, img_h, _ = PRESETS['twitter_landscape']",
         "def money(v):",
         "    return f'${abs(v)/1e9:.2f}B' if abs(v) >= 1e9 else f'${abs(v)/1e6:.0f}M'",
         "films[['title','adjusted_gross','nominal_gross','release_year']].head()"),
    md("## A. Domestic — adjusted vs nominal",
       "The gap between what a film made at the time (gold) and its inflation-adjusted",
       "gross (teal). Domestic (U.S. & Canada) only."),
    code("display(lollipop(",
         "    films, category_col='label', value_col='adjusted_gross', value2_col='nominal_gross',",
         "    value_fmt=money, title='Adjusted vs nominal domestic gross - top 15',",
         "    subtitle='Teal = adjusted (2022 $), gold = nominal (release $)',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Adjusted', value2_label='Nominal', img_width=img_w, img_height=img_h,",
         "))"),
    md("## B. Worldwide — domestic vs international",
       "The reason the domestic chart is only half the story: for most top films the",
       "international (rest-of-world) take dwarfs the domestic one. Gold = domestic,",
       "teal = international. Watch **Ne Zha 2** — a Chinese blockbuster with a huge",
       "international total and almost no domestic gross."),
    code("# Restrict to US-made films so 'domestic' (US & Canada) = the film's home market.",
         "ww = con.execute('''",
         "    WITH us AS (SELECT title, release_year FROM films_genre WHERE is_us=TRUE)",
         "    SELECT w.title, w.release_year, w.domestic_gross, w.foreign_gross, w.worldwide_gross",
         "    FROM films_worldwide w JOIN us ON us.title=w.title AND us.release_year=w.release_year",
         "    ORDER BY w.worldwide_gross DESC LIMIT 15''').df()",
         "ww['label'] = ww['title'] + '  (' + ww['release_year'].astype(str) + ')'",
         "display(lollipop(",
         "    ww, category_col='label', value_col='foreign_gross', value2_col='domestic_gross',",
         "    label_col='worldwide_gross', value_fmt=money,",
         "    title='Hollywood films: home (US/Canada) vs abroad (top 15)',",
         "    subtitle='US-made films only. Gold = home (US & Canada), teal = rest of world; label = worldwide total.',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Rest of world', value2_label='Home', img_width=img_w, img_height=img_h,",
         "))"),
    md("## C. Share of box office earned abroad, by genre",
       "Plain international share per genre (US-made films): of everything the genre",
       "earned worldwide, what fraction came from outside the U.S. & Canada. Sorted",
       "high to low. Each film's gross is attributed to all its genres (so grosses",
       "double-count across genres — fine for a share, see SOURCES.md). The story:",
       "every genre earns most of its money abroad; sci-fi is simply the lowest."),
    code("genre = con.execute('''",
         "    WITH us AS (SELECT title, release_year FROM films_genre WHERE is_us=TRUE)",
         "    SELECT gl.genre AS category, COUNT(*) n,",
         "      ROUND(100.0*SUM(w.foreign_gross)/(SUM(w.domestic_gross)+SUM(w.foreign_gross)),1) AS value",
         "    FROM films_worldwide w",
         "    JOIN us ON us.title=w.title AND us.release_year=w.release_year",
         "    JOIN film_genres_long gl ON gl.title=w.title AND gl.release_year=w.release_year",
         "    GROUP BY gl.genre HAVING COUNT(*)>=10 ORDER BY value DESC''').df()",
         "genre['pct_label'] = genre['value'].apply(lambda v: f'{v:.0f}%')",
         "display(single_ranked_bars(genre, category_col='category', value_col='value',",
         "    total_label_col='pct_label', bar_color='#005F73',",
         "    title='Every blockbuster genre earns most of its money abroad',",
         "    subtitle='Share of worldwide box office earned outside the U.S. & Canada, by genre (top US-made films).',",
         "    img_width=img_w, img_height=img_h))"),
    md("## Cleanup",
       "Close the DuckDB connection so the lock is released for other tools (DBCode,",
       "other notebooks)."),
    code("con.close()",
         "print('connection closed')"),
    md("---",
       "**Next:** `06-viz-social.ipynb` builds the publication versions of these three",
       "charts (full titling/source) and saves them to `outputs/social/`."),
]


# ---------------------------------------------------------------------------
# 06 — VIZ SOCIAL (Pillow lollipop lead chart)
# ---------------------------------------------------------------------------
viz_social = [
    md("# 06 — Social charts (Pillow)",
       "",
       "Three publication-ready charts, each rendered **inline** (then saved to",
       "`outputs/social/`). Workspace rule: `display()` first, then save — a chart is",
       "never saved without being shown.",
       "",
       "1. Worldwide gross — domestic vs international (dumbbell)",
       "2. Which genres travel — international vs domestic index (diverging bars)",
       "3. Biggest *domestic* films, adjusted for inflation (dumbbell)"),
    code(BOOT, "",
         "WORKSPACE = PROJECT.parent.parent",
         "sys.path.insert(0, str(WORKSPACE / 'shared'))",
         "",
         "import duckdb",
         "from src.ingest import load_config",
         "from chart_templates import lollipop, single_ranked_bars",
         "from viz import PRESETS",
         "from IPython.display import display",
         "",
         "cfg = load_config('config.yaml')",
         "# read-only: viz notebooks only read, so they run alongside an open kernel.",
         "con = duckdb.connect(cfg['settings']['duckdb_file'], read_only=True)",
         "img_w, img_h, _ = PRESETS['twitter_landscape']",
         "out = Path(cfg['paths']['outputs_social']); out.mkdir(parents=True, exist_ok=True)",
         "def money(v):",
         "    return f'${v/1e9:.2f}B' if abs(v) >= 1e9 else f'${v/1e6:.0f}M'"),
    md("## 1. Where the money comes from: overseas",
       "Top 15 by worldwide gross. Gold = domestic (US/Canada), teal = international."),
    code("# US-made films only, so 'home' (US & Canada) is the film's actual home market.",
         "ww = con.execute('''",
         "    WITH us AS (SELECT title, release_year FROM films_genre WHERE is_us=TRUE)",
         "    SELECT w.title, w.release_year, w.domestic_gross, w.foreign_gross, w.worldwide_gross",
         "    FROM films_worldwide w JOIN us ON us.title=w.title AND us.release_year=w.release_year",
         "    ORDER BY w.worldwide_gross DESC LIMIT 15''').df()",
         "ww['label'] = ww['title'] + '  (' + ww['release_year'].astype(str) + ')'",
         "img2 = lollipop(ww, category_col='label', value_col='foreign_gross', value2_col='domestic_gross',",
         "    label_col='worldwide_gross',  # ranked by worldwide total; label that so it reads as sorted",
         "    value_fmt=money, title=\"Hollywood's biggest films make most of their money abroad\",",
         "    subtitle='Top 15 U.S.-produced films by worldwide gross (nominal $), highest first. Gold = home (U.S. & Canada), teal = rest of world; label = worldwide total.',",
         "    source='Box Office Mojo, Top Lifetime Grosses (Worldwide) + TMDB origin country — as of Sep 2026',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Rest of world', value2_label='Home (US/Canada)',",
         "    img_width=img_w, img_height=img_h)",
         "display(img2)",
         "img2.save(out / '02_worldwide_domestic_vs_international.png')"),
    md("## 2. Share of box office earned abroad, by genre",
       "Of everything a genre earned worldwide, what fraction came from outside the",
       "U.S. & Canada (US-made films). Every genre earns most of its money abroad;",
       "sci-fi is simply the lowest. Plain share — no index, no zero-line."),
    code("genre = con.execute('''",
         "    WITH us AS (SELECT title, release_year FROM films_genre WHERE is_us=TRUE)",
         "    SELECT gl.genre AS category, COUNT(*) n,",
         "      ROUND(100.0*SUM(w.foreign_gross)/(SUM(w.domestic_gross)+SUM(w.foreign_gross)),1) AS value",
         "    FROM films_worldwide w",
         "    JOIN us ON us.title=w.title AND us.release_year=w.release_year",
         "    JOIN film_genres_long gl ON gl.title=w.title AND gl.release_year=w.release_year",
         "    GROUP BY gl.genre HAVING COUNT(*)>=10 ORDER BY value DESC''').df()",
         "genre['pct_label'] = genre['value'].apply(lambda v: f'{v:.0f}%')",
         "img3 = single_ranked_bars(genre, category_col='category', value_col='value',",
         "    total_label_col='pct_label', bar_color='#005F73',",
         "    title='Every blockbuster genre earns most of its money abroad',",
         "    subtitle='Share of worldwide box office earned OUTSIDE the U.S. & Canada, by genre (top U.S.-made films). Even the lowest — sci-fi — takes ~61% overseas.',",
         "    source='Box Office Mojo (Worldwide) + TMDB genres/origin — as of Sep 2026',",
         "    img_width=img_w, img_height=img_h)",
         "display(img3)",
         "img3.save(out / '03_genre_share_earned_abroad.png')"),
    md("## 3. Biggest *domestic* films, adjusted for inflation",
       "A different question: within the U.S. & Canada, adjusted for ticket-price",
       "inflation. Teal = adjusted (2022 $), gold = nominal (release $)."),
    code("dom = con.execute('''SELECT title, adjusted_gross, nominal_gross, release_year",
         "    FROM films_adjusted ORDER BY adjusted_gross DESC LIMIT 15''').df()",
         "dom['label'] = dom['title'] + '  (' + dom['release_year'].astype(str) + ')'",
         "img1 = lollipop(dom, category_col='label', value_col='adjusted_gross', value2_col='nominal_gross',",
         "    value_fmt=money, title='The biggest DOMESTIC films of all time, adjusted for inflation',",
         "    subtitle='U.S. & Canada only. Teal = adjusted to 2022 $, gold = nominal (release $) — the gap is a century of ticket-price inflation.',",
         "    source='Box Office Mojo, Top Lifetime Adjusted Grosses (domestic, adj. to 2022) — as of Sep 2026',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Adjusted (2022 $)', value2_label='Nominal (release $)',",
         "    img_width=img_w, img_height=img_h)",
         "display(img1)",
         "img1.save(out / '01_domestic_adjusted_vs_nominal.png')"),
    md("---",
       "Three charts written to `outputs/social/`. Watermark `@unwelcomedata`, brand",
       "palette, `twitter_landscape` preset."),
    md("## Cleanup",
       "Close the DuckDB connection so the lock is released for other tools."),
    code("con.close()",
         "print('connection closed')"),
]


if __name__ == "__main__":
    write("01-ingest.ipynb", ingest)
    write("02-clean.ipynb", clean)
    write("03-prepare.ipynb", prepare)
    write("04-viz.ipynb", viz)
    write("06-viz-social.ipynb", viz_social)
    print("done")
