#!/usr/bin/env python
"""One-off: write the numbered pipeline notebooks with real, runnable, project-
specific walkthrough cells (so the notebooks ARE the process record).

This mirrors the logic in scripts/ingest.py + scripts/make_charts.py but laid out
as the numbered pipeline a reader can step through:
    00-explore  (left as-is: DuckDB sandbox)
    01-ingest   fetch BOM adjusted chart -> data/raw/
    02-clean    parse + clean in DuckDB -> films_adjusted (+ _sources)
    03-prepare  package the export (CSV + codebook)
    04-viz      matplotlib exploration (adjusted vs nominal)
    06-viz-social  the shared lollipop dumbbell lead chart (inline + saved)

Run once: .venv/bin/python scripts/_build_notebooks.py
"""

from __future__ import annotations

import json
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent.parent / "notebooks"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": _src(lines)}


def _src(lines: tuple[str, ...]) -> list[str]:
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def write(name: str, cells: list[dict]) -> None:
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    (NB_DIR / name).write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {name} ({len(cells)} cells)")


BOOT = (
    "import sys, os\n"
    "from pathlib import Path\n"
    "PROJECT = Path.cwd()\n"
    "while not (PROJECT / 'config.yaml').exists() and PROJECT != PROJECT.parent:\n"
    "    PROJECT = PROJECT.parent\n"
    "os.chdir(PROJECT)\n"
    "sys.path.insert(0, str(PROJECT))"
)


# ---------------------------------------------------------------------------
# 01 — INGEST
# ---------------------------------------------------------------------------
ingest = [
    md("# 01 — Ingest",
       "",
       "Fetch the raw source and land it in `data/raw/` **untouched**.",
       "",
       "**Source:** Box Office Mojo — *Top Lifetime Adjusted Grosses* (domestic). The",
       "`?adjust_gross_to=2022` query param makes the page return each film's",
       "inflation-adjusted gross (in 2022 dollars) alongside its nominal gross,",
       "estimated tickets sold, and release year. With that param the page is static",
       "(no JS needed)."),
    code(BOOT, "",
         "import pandas as pd",
         "from io import StringIO",
         "from src.ingest import load_config, fetch_html",
         "",
         "cfg = load_config('config.yaml')",
         "src = cfg['sources']['bom_adjusted']",
         "url = src['url']",
         "print('Source URL:', url)"),
    md("## Fetch and cache the raw HTML",
       "Save the page to `data/raw/` so the raw source is preserved and re-runs are",
       "offline."),
    code("raw_path = Path(cfg['paths']['data_raw']) / 'bom_top_lifetime_adjusted_2022.html'",
         "raw_path.parent.mkdir(parents=True, exist_ok=True)",
         "",
         "if raw_path.exists():",
         "    print('Using cached raw HTML:', raw_path)",
         "    html = raw_path.read_text(encoding='utf-8')",
         "else:",
         "    html = fetch_html(url)",
         "    raw_path.write_text(html, encoding='utf-8')",
         "    print('Saved raw HTML ->', raw_path)",
         "",
         "print(f'{len(html):,} bytes')"),
    md("## Parse the chart table",
       "The page has a single table: Rank, Title, Adj. Lifetime Gross, Lifetime Gross,",
       "Est. Num Tickets, Year."),
    code("raw = pd.read_html(StringIO(html))[0]",
         "print(raw.shape)",
         "raw.head(10)"),
    md("## Also fetch the WORLDWIDE chart",
       "The adjusted chart above is **domestic only** (U.S. & Canada). To compare",
       "domestic vs. international we also pull Box Office Mojo's worldwide chart,",
       "which splits each film into worldwide / domestic / foreign gross."),
    code("ww_url = cfg['sources']['bom_worldwide']['url']",
         "ww_path = Path(cfg['paths']['data_raw']) / 'bom_ww_top_lifetime.html'",
         "if ww_path.exists():",
         "    ww_html = ww_path.read_text(encoding='utf-8')",
         "else:",
         "    ww_html = fetch_html(ww_url)",
         "    ww_path.write_text(ww_html, encoding='utf-8')",
         "ww_raw = pd.read_html(StringIO(ww_html))[0]",
         "print(ww_raw.shape)",
         "ww_raw.head(5)"),
    md("---",
       "**Next:** `02-clean.ipynb` loads these into DuckDB, cleans them, and enriches",
       "with genre from TMDB.",
       "",
       "Nothing here modified data — the raw HTML in `data/raw/` is untouched."),
]


# ---------------------------------------------------------------------------
# 02 — CLEAN
# ---------------------------------------------------------------------------
clean = [
    md("# 02 — Clean & Standardize",
       "",
       "Load the raw chart into DuckDB and clean it **in SQL** (workspace norm):",
       "strip `$`/commas, cast to numeric, derive `decade` and the `inflation_multiple`",
       "(adjusted / nominal). Result: the `films_adjusted` table."),
    code(BOOT, "",
         "import pandas as pd",
         "from io import StringIO",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection, load_to_duckdb, run_sql, register_source, save_interim",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "",
         "# Reload the raw HTML parsed in 01 into a raw DuckDB table.",
         "html = (Path(cfg['paths']['data_raw']) / 'bom_top_lifetime_adjusted_2022.html').read_text(encoding='utf-8')",
         "raw = pd.read_html(StringIO(html))[0]",
         "load_to_duckdb(raw, 'bom_raw', con)",
         "print('bom_raw:', con.execute('SELECT COUNT(*) FROM bom_raw').fetchone()[0], 'rows')"),
    md("## Clean in DuckDB",
       "Money strings (`$1,895,421,694`) become `BIGINT`; `decade` uses integer",
       "division; `inflation_multiple` = adjusted / nominal (how many times the film's",
       "original take the adjusted figure represents)."),
    code("films = run_sql('''",
         "    SELECT",
         "        CAST(\"Rank\" AS INTEGER)                                   AS rank_adjusted,",
         "        \"Title\"                                                   AS title,",
         "        CAST(REGEXP_REPLACE(\"Adj. Lifetime Gross\", '[$,]', '', 'g') AS BIGINT) AS adjusted_gross,",
         "        CAST(REGEXP_REPLACE(\"Lifetime Gross\",       '[$,]', '', 'g') AS BIGINT) AS nominal_gross,",
         "        CAST(\"Est. Num Tickets\" AS BIGINT)                        AS est_tickets,",
         "        CAST(\"Year\" AS INTEGER)                                   AS release_year,",
         "        (CAST(\"Year\" AS INTEGER) // 10) * 10                      AS decade,",
         "        ROUND(",
         "            CAST(REGEXP_REPLACE(\"Adj. Lifetime Gross\", '[$,]', '', 'g') AS DOUBLE)",
         "            / NULLIF(CAST(REGEXP_REPLACE(\"Lifetime Gross\", '[$,]', '', 'g') AS DOUBLE), 0),",
         "            2) AS inflation_multiple",
         "    FROM bom_raw",
         "    ORDER BY adjusted_gross DESC",
         "''', con)",
         "load_to_duckdb(films, 'films_adjusted', con)",
         "print(films.shape)",
         "films.head(10)"),
    md("## Quick sanity checks"),
    code("# The classics should dominate the adjusted board; recent blockbusters have",
         "# the smallest inflation multiples (little time for ticket prices to rise).",
         "print('Top adjusted:', films.iloc[0]['title'], films.iloc[0]['release_year'])",
         "print('No nulls in key cols:',",
         "      films[['adjusted_gross','nominal_gross','est_tickets','release_year']].notna().all().all())",
         "films[['title','release_year','inflation_multiple']].sort_values('inflation_multiple').head(5)"),
    md("## Clean the WORLDWIDE chart (domestic vs international split)",
       "Same money-string cleaning; a bare `-` (no gross in a market) becomes NULL.",
       "Produces `films_worldwide` with domestic/foreign/worldwide gross + the split."),
    code("ww_html = (Path(cfg['paths']['data_raw']) / 'bom_ww_top_lifetime.html').read_text(encoding='utf-8')",
         "ww_raw = pd.read_html(StringIO(ww_html))[0]",
         "load_to_duckdb(ww_raw, 'bom_ww_raw', con)",
         "ww = run_sql('''",
         "    WITH cleaned AS (",
         "        SELECT CAST(\"Rank\" AS INTEGER) AS rank_worldwide, \"Title\" AS title,",
         "               CAST(\"Year\" AS INTEGER) AS release_year,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Worldwide Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS worldwide_gross,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Domestic Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS domestic_gross,",
         "               TRY_CAST(NULLIF(REGEXP_REPLACE(\"Foreign Lifetime Gross\",'[$,]','','g'),'-') AS BIGINT) AS foreign_gross",
         "        FROM bom_ww_raw)",
         "    SELECT rank_worldwide, title, worldwide_gross, domestic_gross, foreign_gross, release_year,",
         "        ROUND(100.0*domestic_gross/NULLIF(worldwide_gross,0),1) AS domestic_pct,",
         "        ROUND(100.0*foreign_gross /NULLIF(worldwide_gross,0),1) AS foreign_pct",
         "    FROM cleaned ORDER BY worldwide_gross DESC''', con)",
         "load_to_duckdb(ww, 'films_worldwide', con)",
         "print('most international (lowest domestic %):')",
         "print(ww.nsmallest(5,'domestic_pct')[['title','release_year','worldwide_gross','domestic_pct']].to_string(index=False))",
         "ww.head()"),
    md("## Enrich with genre (TMDB API)",
       "",
       "Box Office Mojo has no genre, so we enrich each film with genre from **TMDB**",
       "(themoviedb.org) via its REST API. Requires a free `TMDB_API_KEY` in `.env`",
       "(gitignored).",
       "",
       "**What happens under the hood:** for each film we call TMDB's",
       "`GET /3/search/movie?query=<title>&year=<year>`, take the first result, and map",
       "its `genre_ids` to names via `GET /3/genre/movie/list`. That HTTP call lives in",
       "`src/ingest.py` → `tmdb_lookup_movie()` (kept in `src/` per workspace norms, and",
       "**cached to `data/raw/tmdb/<film>.json`** so re-runs are offline and don't re-hit",
       "the API). The next cell makes **one call explicitly** so you can see exactly what",
       "the API returns; the cell after that loops the cached helper over all films."),
    md("### One TMDB call, spelled out",
       "The raw request + response for a single film, so the mechanics are visible in",
       "the notebook (this is the same call `tmdb_lookup_movie()` makes internally)."),
    code("import requests",
         "from src.ingest import load_env, tmdb_genre_map, tmdb_lookup_movie",
         "load_env('.env')",
         "api_key = os.environ.get('TMDB_API_KEY')",
         "assert api_key, 'TMDB_API_KEY missing from .env'",
         "",
         "# raw search call for one film",
         "demo = requests.get('https://api.themoviedb.org/3/search/movie',",
         "                    params={'api_key': api_key, 'query': 'Avatar', 'year': 2009}, timeout=20)",
         "top = demo.json()['results'][0]",
         "print('HTTP', demo.status_code, '| result:', top['title'], top['release_date'])",
         "print('raw genre_ids:', top['genre_ids'])",
         "# genre id -> name map (also from TMDB)",
         "gmap = tmdb_genre_map(api_key)",
         "print('mapped genres:', [gmap[i] for i in top['genre_ids']])"),
    md("### Now enrich every film",
       "Loop the cached helper over all films from both boards (deduped by title+year).",
       "First run hits the API (~321 calls, rate-limited); re-runs read the JSON cache in",
       "`data/raw/tmdb/`. Builds `films_genre` (one row per film) and `film_genres_long`",
       "(one row per film x genre) — the latter drives the genre market-split analysis."),
    code("titles = con.execute('''",
         "    SELECT DISTINCT title, release_year FROM (",
         "        SELECT title, release_year FROM films_worldwide",
         "        UNION SELECT title, release_year FROM films_adjusted)''').df()",
         "recs = [tmdb_lookup_movie(r['title'], int(r['release_year']), api_key, cfg) for _, r in titles.iterrows()]",
         "genre_df = pd.DataFrame(recs)",
         "genre_df['genres_str'] = genre_df['genres'].apply(lambda g: ', '.join(g) if g else None)",
         "films_genre = genre_df.drop(columns=['genres']).rename(columns={'year':'release_year'})",
         "load_to_duckdb(films_genre, 'films_genre', con)",
         "",
         "long_rows = [{'title':r['title'],'release_year':r['year'],'genre':g} for r in recs for g in r['genres']]",
         "film_genres_long = pd.DataFrame(long_rows)",
         "load_to_duckdb(film_genres_long, 'film_genres_long', con)",
         "print(f'{films_genre[\"matched\"].sum()}/{len(films_genre)} matched; {len(film_genres_long)} film-genre rows')",
         "films_genre['primary_genre'].value_counts().head(8)"),
    md("## Save interim + register provenance"),
    code("save_interim(films, cfg, 'films_adjusted.parquet')",
         "save_interim(ww, cfg, 'films_worldwide.parquet')",
         "save_interim(films_genre, cfg, 'films_genre.parquet')",
         "save_interim(film_genres_long, cfg, 'film_genres_long.parquet')",
         "",
         "register_source(con, 'films_adjusted',",
         "    name='Box Office Mojo - Top Lifetime Adjusted Grosses (domestic)',",
         "    url=cfg['sources']['bom_adjusted']['url'], license='Data (c) IMDb/Box Office Mojo.',",
         "    notes='Domestic (US/Canada). Adjusted to 2022 $ via tickets x 2022 avg ticket price (ticket-price inflation, NOT CPI).',",
         "    methodology='Tickets sold x reference-year avg price; lifetime totals include re-releases.',",
         "    series_breaks='Nominal grosses are year-of-release dollars, not comparable across eras.')",
         "register_source(con, 'films_worldwide',",
         "    name='Box Office Mojo - Top Lifetime Grosses (Worldwide)',",
         "    url=cfg['sources']['bom_worldwide']['url'], license='Data (c) IMDb/Box Office Mojo.',",
         "    notes='Worldwide/domestic/foreign lifetime gross (NOMINAL $) + split. Domestic = US & Canada.',",
         "    methodology='Studio-reported theatrical receipts; lifetime totals include re-releases.',",
         "    series_breaks='Nominal dollars; worldwide totals favor recent wide-release films.')",
         "register_source(con, 'films_genre',",
         "    name='TMDB - film genres', url='https://www.themoviedb.org/',",
         "    license='TMDB API; non-commercial attribution.',",
         "    notes='Genre(s) per film matched by title+year. Multi-genre; used as a ratio in the market split.',",
         "    methodology='TMDB /search/movie by title+year, first result.', series_breaks='')",
         "print(con.execute('SELECT duckdb_table, source_name FROM _sources ORDER BY duckdb_table').df().to_string(index=False))"),
    md("---",
       "**Next:** `03-prepare.ipynb` packages the three exports + codebooks."),
    md("## Cleanup",
       "Close the DuckDB connection so the write lock is released."),
    code("con.close()",
         "print('connection closed')"),
]


# ---------------------------------------------------------------------------
# 03 — PREPARE
# ---------------------------------------------------------------------------
prepare = [
    md("# 03 — Prepare & Export",
       "",
       "Package the cleaned `films_adjusted` table as the published dataset: CSV",
       "(+ Excel/Parquet) with a plain-English codebook for every column."),
    code(BOOT, "",
         "import pandas as pd",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection",
         "from src.prepare import package_dataset",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "films = con.execute('SELECT * FROM films_adjusted ORDER BY adjusted_gross DESC').df()",
         "worldwide = con.execute('SELECT * FROM films_worldwide ORDER BY worldwide_gross DESC').df()",
         "genre = con.execute('SELECT * FROM films_genre ORDER BY title').df()",
         "print('adjusted', films.shape, '| worldwide', worldwide.shape, '| genre', genre.shape)"),
    md("## Codebook — a plain-English description for every column"),
    code("codebook = {",
         "    'rank_adjusted':     'Rank by inflation-adjusted domestic gross (1 = highest).',",
         "    'title':             'Film title.',",
         "    'adjusted_gross':    'Domestic lifetime gross adjusted to 2022 dollars via ticket-price inflation (USD).',",
         "    'nominal_gross':     'Domestic lifetime gross in year-of-release dollars, as originally reported (USD).',",
         "    'est_tickets':       'Estimated number of tickets sold over the film lifetime (Box Office Mojo estimate).',",
         "    'release_year':      'Year of the film original theatrical release.',",
         "    'decade':            'Release decade (release_year rounded down to the nearest 10).',",
         "    'inflation_multiple':'adjusted_gross / nominal_gross - how many times its original take the adjusted figure represents.',",
         "}",
         "",
         "notes = '''",
         "Source: Box Office Mojo, Top Lifetime Adjusted Grosses (domestic, US/Canada), adjusted to 2022 dollars.",
         "URL: https://www.boxofficemojo.com/chart/top_lifetime_gross_adjusted/?adjust_gross_to=2022",
         "",
         "Method: adjusted gross = estimated tickets sold x the 2022 average ticket price (ticket-price inflation,",
         "NOT CPI). Domestic only. A film lifetime total includes re-release grosses, which inflates some classics.",
         "Nominal grosses are in year-of-release dollars and are not comparable across eras without the adjustment.",
         "'''",
        "written = package_dataset(films, cfg, name='highest_grossing_films_v1', codebook=codebook, notes=notes)",
         "written"),
    md("## Package the worldwide + genre exports"),
    code("ww_codebook = {",
         "    'rank_worldwide': 'Rank by worldwide lifetime gross (1 = highest).',",
         "    'title': 'Film title.',",
         "    'worldwide_gross': 'Worldwide lifetime gross, nominal USD (domestic + foreign).',",
         "    'domestic_gross': 'Domestic (U.S. & Canada) lifetime gross, nominal USD.',",
         "    'foreign_gross': 'International (rest-of-world) lifetime gross, nominal USD.',",
         "    'release_year': 'Year of original theatrical release.',",
         "    'domestic_pct': 'Domestic gross as a percent of worldwide.',",
         "    'foreign_pct': 'International gross as a percent of worldwide.',",
         "}",
         "ww_notes = '''Source: Box Office Mojo, Top Lifetime Grosses (Worldwide).",
         "Nominal (year-of-release) dollars, NOT inflation-adjusted. Domestic = US & Canada.'''",
         "package_dataset(worldwide, cfg, name='films_worldwide_v1', codebook=ww_codebook, notes=ww_notes)",
         "",
         "genre_codebook = {",
         "    'title': 'Film title.', 'release_year': 'Release year (match key).',",
         "    'tmdb_id': 'TMDB movie id.', 'tmdb_title': 'Title as returned by TMDB.',",
         "    'primary_genre': \"TMDB's first-listed genre for the film.\",",
         "    'genres_str': 'All TMDB genres, comma-separated.',",
         "    'matched': 'True if a TMDB result was found for title+year.',",
         "}",
         "genre_notes = '''Source: TMDB (themoviedb.org), matched by title + release year.",
         "Genres are TMDB editorial tags; most films have several. Used as a ratio in the",
         "genre market-split analysis (see SOURCES.md for the multi-genre attribution note).'''",
         "package_dataset(genre, cfg, name='films_genre_v1', codebook=genre_codebook, notes=genre_notes)"),
    md("---",
       "**Next:** `04-viz.ipynb` (exploration) and `06-viz-social.ipynb` (the three social charts)."),
    md("## Cleanup"),
    code("con.close()",
         "print('connection closed')"),
]


# ---------------------------------------------------------------------------
# 04 — VIZ (matplotlib exploration)
# ---------------------------------------------------------------------------
viz = [
    md("# 04 — Explore visually",
       "",
       "Quick exploration of the story before the publication chart, using the shared",
       "Pillow `lollipop` template in both modes: single-value (lollipop) and two-value",
       "(dumbbell). Charts render inline via `display()`.",
       "",
       "> Note: this project renders with the shared **Pillow** factory rather than",
       "> matplotlib. (matplotlib does not run in this project's Python 3.14 venv — a",
       "> known `MarkerStyle` deepcopy recursion during axis-tick rendering — and the",
       "> publication path is Pillow anyway, so matplotlib isn't a dependency here.)"),
    code(BOOT, "",
         "WORKSPACE = PROJECT.parent.parent",
         "sys.path.insert(0, str(WORKSPACE / 'shared'))",
         "",
         "import pandas as pd",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection",
         "from chart_templates import lollipop",
         "from viz import PRESETS",
         "from IPython.display import display",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "films = con.execute('SELECT * FROM films_adjusted ORDER BY adjusted_gross DESC LIMIT 15').df()",
         "con.close()",
         "films['label'] = films['title'] + '  (' + films['release_year'].astype(str) + ')'",
         "img_w, img_h, _ = PRESETS['twitter_landscape']",
         "def money(v):",
         "    return f'${v/1e9:.2f}B' if v >= 1e9 else f'${v/1e6:.0f}M'",
         "films[['title','adjusted_gross','nominal_gross','release_year']].head()"),
    md("## Single-value lollipop — adjusted gross only",
       "The ranked adjusted board on its own (lollipop mode)."),
    code("display(lollipop(",
         "    films, category_col='label', value_col='adjusted_gross', value_fmt=money,",
         "    title='Top 15 films by inflation-adjusted domestic gross',",
         "    subtitle='Box Office Mojo, adjusted to 2022 dollars',",
         "    dot_color='#005F73', img_width=img_w, img_height=img_h,",
         "))"),
    md("## Dumbbell — adjusted vs nominal",
       "Adding `value2_col` turns it into a dumbbell: the gap between what a film made",
       "at the time (gold) and its adjusted gross (teal) is the inflation effect."),
    code("display(lollipop(",
         "    films, category_col='label', value_col='adjusted_gross', value2_col='nominal_gross',",
         "    value_fmt=money, title='Adjusted vs nominal domestic gross - top 15',",
         "    subtitle='Teal = adjusted (2022 $), gold = nominal (release $)',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Adjusted', value2_label='Nominal', img_width=img_w, img_height=img_h,",
         "))"),
    md("---",
       "**Next:** `06-viz-social.ipynb` builds the final publication chart (the same",
       "dumbbell, with full titling/source) and saves it to `outputs/social/`."),
]


# ---------------------------------------------------------------------------
# 06 — VIZ SOCIAL (Pillow lollipop lead chart)
# ---------------------------------------------------------------------------
viz_social = [
    md("# 06 — Social charts (Pillow)",
       "",
       "Three publication-ready charts, each rendered **inline** (then saved to",
       "`outputs/social/`). Workspace rule: `display()` first, then save — a chart is",
       "never saved without being shown.",
       "",
       "1. Worldwide gross — domestic vs international (dumbbell)",
       "2. Which genres travel — international vs domestic index (diverging bars)",
       "3. Biggest *domestic* films, adjusted for inflation (dumbbell)"),
    code(BOOT, "",
         "WORKSPACE = PROJECT.parent.parent",
         "sys.path.insert(0, str(WORKSPACE / 'shared'))",
         "",
         "from src.ingest import load_config",
         "from src.clean_quality import get_connection",
         "from chart_templates import lollipop, diverging_bars",
         "from viz import PRESETS",
         "from IPython.display import display",
         "",
         "cfg = load_config('config.yaml')",
         "con = get_connection(cfg)",
         "img_w, img_h, _ = PRESETS['twitter_landscape']",
         "out = Path(cfg['paths']['outputs_social']); out.mkdir(parents=True, exist_ok=True)",
         "def money(v):",
         "    return f'${v/1e9:.2f}B' if abs(v) >= 1e9 else f'${v/1e6:.0f}M'"),
    md("## 1. Where the money comes from: overseas",
       "Top 15 by worldwide gross. Gold = domestic (US/Canada), teal = international."),
    code("ww = con.execute('''SELECT title, release_year, domestic_gross, foreign_gross, worldwide_gross",
         "    FROM films_worldwide ORDER BY worldwide_gross DESC LIMIT 15''').df()",
         "ww['label'] = ww['title'] + '  (' + ww['release_year'].astype(str) + ')'",
         "img2 = lollipop(ww, category_col='label', value_col='foreign_gross', value2_col='domestic_gross',",
         "    value_fmt=money, title='Where the money really comes from: overseas',",
         "    subtitle='Top 15 films by worldwide gross (nominal $). Teal = international (rest of world), gold = domestic (U.S. & Canada).',",
         "    source='Box Office Mojo, Top Lifetime Grosses (Worldwide) — as of Sep 2026',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='International', value2_label='Domestic (US/Canada)',",
         "    img_width=img_w, img_height=img_h)",
         "display(img2)",
         "img2.save(out / '02_worldwide_domestic_vs_international.png')"),
    md("## 2. Which genres travel?",
       "Each genre's share of international box office relative to domestic (top-200",
       "worldwide films, genres with 10+ films). Right = over-indexes internationally."),
    code("genre = con.execute('''",
         "    WITH fg AS (SELECT w.domestic_gross, w.foreign_gross, g.genre",
         "                FROM films_worldwide w JOIN film_genres_long g",
         "                  ON g.title=w.title AND g.release_year=w.release_year),",
         "         tot AS (SELECT SUM(domestic_gross) d, SUM(foreign_gross) f FROM fg),",
         "         bygenre AS (SELECT genre, COUNT(*) n, SUM(domestic_gross) dom, SUM(foreign_gross) intl",
         "                     FROM fg GROUP BY genre HAVING COUNT(*)>=10)",
         "    SELECT genre AS category,",
         "           ROUND((intl/(SELECT f FROM tot))/NULLIF(dom/(SELECT d FROM tot),0)-1,3) AS value",
         "    FROM bygenre ORDER BY value DESC''').df()",
         "genre['label'] = genre['value'].apply(lambda v: f\"{'+' if v>=0 else ''}{v*100:.0f}%\")",
         "img3 = diverging_bars(genre, category_col='category', value_col='value', label_col='label',",
         "    title='Which genres travel? Blockbuster genres that skew overseas vs. at home',",
         "    subtitle='Share of international box office relative to domestic, top-200 worldwide films (10+ films). Right = over-indexes internationally.',",
         "    source='Box Office Mojo (Worldwide) + TMDB genres — as of Sep 2026',",
         "    pos_color='#005F73', neg_color='#AE2012', img_width=img_w, img_height=img_h)",
         "display(img3)",
         "img3.save(out / '03_genre_international_vs_domestic_index.png')"),
    md("## 3. Biggest *domestic* films, adjusted for inflation",
       "A different question: within the U.S. & Canada, adjusted for ticket-price",
       "inflation. Teal = adjusted (2022 $), gold = nominal (release $)."),
    code("dom = con.execute('''SELECT title, adjusted_gross, nominal_gross, release_year",
         "    FROM films_adjusted ORDER BY adjusted_gross DESC LIMIT 15''').df()",
         "dom['label'] = dom['title'] + '  (' + dom['release_year'].astype(str) + ')'",
         "img1 = lollipop(dom, category_col='label', value_col='adjusted_gross', value2_col='nominal_gross',",
         "    value_fmt=money, title='The biggest DOMESTIC films of all time, adjusted for inflation',",
         "    subtitle='U.S. & Canada only. Teal = adjusted to 2022 $, gold = nominal (release $).',",
         "    source='Box Office Mojo, Top Lifetime Adjusted Grosses (domestic, adj. to 2022) — as of Sep 2026',",
         "    dot_color='#005F73', dot2_color='#EE9B00',",
         "    value_label='Adjusted (2022 $)', value2_label='Nominal (release $)',",
         "    img_width=img_w, img_height=img_h)",
         "display(img1)",
         "img1.save(out / '01_domestic_adjusted_vs_nominal.png')",
         "con.close()"),
    md("---",
       "Three charts written to `outputs/social/`. Watermark `@unwelcomedata`, brand",
       "palette, `twitter_landscape` preset."),
]


if __name__ == "__main__":
    write("01-ingest.ipynb", ingest)
    write("02-clean.ipynb", clean)
    write("03-prepare.ipynb", prepare)
    write("04-viz.ipynb", viz)
    write("06-viz-social.ipynb", viz_social)
    print("done")
